# Generated by Django 3.1.2 on 2020-11-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentno',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterIndexTogether(
            name='students',
            index_together={('Tea', 'sid')},
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['title'], name='api_news_title_4772e8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['title'], name='api_notific_title_2cf984_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['title'], name='api_paper_title_b3a1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['realname'], name='by_user_realnam_e7d849_idx'),
        ),
    ]
