# Generated by Django 3.1.2 on 2020-11-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201120_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('Tea', 'sid')},
        ),
    ]
