# Generated by Django 3.1.2 on 2020-11-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201120_1727'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='api_news_title_4772e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_notific_title_2cf984_idx',
        ),
        migrations.RemoveIndex(
            model_name='paper',
            name='api_paper_title_b3a1f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='by_user_realnam_e7d849_idx',
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['sid'], name='api_student_sid_feeb7e_idx'),
        ),
    ]
