# Generated by Django 3.1.2 on 2020-11-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201120_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'paper')},
        ),
    ]
