# Generated by Django 3.1.2 on 2020-11-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='api_news_title_4772e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='api_notific_title_2cf984_idx',
        ),
        migrations.RemoveIndex(
            model_name='paper',
            name='api_paper_title_b3a1f1_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='studentno',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['title'], name='cimp_News_title_b10151_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['title'], name='cimp_Notifi_title_b9e692_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['title'], name='cimp_Paper_title_f13741_idx'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='cimp_News',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='cimp_Notification',
        ),
        migrations.AlterModelTable(
            name='paper',
            table='cimp_Paper',
        ),
        migrations.AlterModelTable(
            name='user',
            table='cimp_user',
        ),
    ]
