# Generated by Django 3.1.2 on 2020-11-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='likes',
            index_together={('user', 'paper')},
        ),
    ]
