# Generated by Django 3.1.2 on 2020-11-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201121_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'paper')},
        ),
    ]
