# Generated by Django 3.1.2 on 2020-11-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201120_1143'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='students',
            index_together={('Tea', 'sid')},
        ),
    ]
