# Generated by Django 3.1.2 on 2020-11-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201120_1656'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['realname'], name='cimp_user_realnam_3b4c6c_idx'),
        ),
    ]
