# Generated by Django 3.1.2 on 2020-11-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201120_1727'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='cimp_News_title_b10151_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='cimp_Notifi_title_b9e692_idx',
        ),
        migrations.RemoveIndex(
            model_name='paper',
            name='cimp_Paper_title_f13741_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='cimp_user_realnam_3b4c6c_idx',
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['sid'], name='api_student_sid_feeb7e_idx'),
        ),
    ]
