# Generated by Django 3.1.2 on 2020-10-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='creator',
            new_name='user',
        ),
    ]
