# Generated by Django 3.1.2 on 2020-10-30 03:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_submitdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiondata', models.DateTimeField(default=datetime.datetime.now)),
                ('actionname', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.workflow')),
            ],
        ),
        migrations.DeleteModel(
            name='Submitdata',
        ),
    ]
