# Generated by Django 3.1.2 on 2020-10-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201030_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstep',
            name='name',
            field=models.CharField(default='备注', max_length=20),
        ),
    ]
