# Generated by Django 3.1.2 on 2020-10-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workstep_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstep',
            old_name='actiondata',
            new_name='actiondate',
        ),
    ]
