# Generated by Django 3.1.2 on 2020-11-15 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201108_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paper'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
