# Generated by Django 3.1.2 on 2020-11-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201115_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
